package com.nan.ia.server.db.entities;

// Generated 2015-5-27 14:32:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountBookDeleteTbl generated by hbm2java
 */
@Entity
@Table(name = "account_book_delete_tbl", catalog = "intimate_account_db")
public class AccountBookDeleteTbl implements java.io.Serializable {

	private int accountBookId;
	private int deleteUserId;
	private Date deleteTime;

	public AccountBookDeleteTbl() {
	}

	public AccountBookDeleteTbl(int accountBookId, int deleteUserId,
			Date deleteTime) {
		this.accountBookId = accountBookId;
		this.deleteUserId = deleteUserId;
		this.deleteTime = deleteTime;
	}

	@Id
	@Column(name = "account_book_id", unique = true, nullable = false)
	public int getAccountBookId() {
		return this.accountBookId;
	}

	public void setAccountBookId(int accountBookId) {
		this.accountBookId = accountBookId;
	}

	@Column(name = "delete_user_id", nullable = false)
	public int getDeleteUserId() {
		return this.deleteUserId;
	}

	public void setDeleteUserId(int deleteUserId) {
		this.deleteUserId = deleteUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_time", nullable = false, length = 19)
	public Date getDeleteTime() {
		return this.deleteTime;
	}

	public void setDeleteTime(Date deleteTime) {
		this.deleteTime = deleteTime;
	}

}
