package com.nan.ia.server.db.entities;

// Generated 2015-5-18 15:27:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountItemTbl generated by hbm2java
 */
@Entity
@Table(name = "account_item_tbl", catalog = "intimate_account_db")
public class AccountItemTbl implements java.io.Serializable {

	private Integer accountItemId;
	private int accountBookId;
	private int accountCategoryId;
	private Integer waterValue;
	private String description;
	private Date recordTime;
	private int createUserId;
	private Date createTime;
	private Date updateTime;

	public AccountItemTbl() {
	}

	public AccountItemTbl(int accountBookId, int accountCategoryId,
			Date recordTime, int createUserId, Date createTime, Date updateTime) {
		this.accountBookId = accountBookId;
		this.accountCategoryId = accountCategoryId;
		this.recordTime = recordTime;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public AccountItemTbl(int accountBookId, int accountCategoryId,
			Integer waterValue, String description, Date recordTime,
			int createUserId, Date createTime, Date updateTime) {
		this.accountBookId = accountBookId;
		this.accountCategoryId = accountCategoryId;
		this.waterValue = waterValue;
		this.description = description;
		this.recordTime = recordTime;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "account_item_id", unique = true, nullable = false)
	public Integer getAccountItemId() {
		return this.accountItemId;
	}

	public void setAccountItemId(Integer accountItemId) {
		this.accountItemId = accountItemId;
	}

	@Column(name = "account_book_id", nullable = false)
	public int getAccountBookId() {
		return this.accountBookId;
	}

	public void setAccountBookId(int accountBookId) {
		this.accountBookId = accountBookId;
	}

	@Column(name = "account_category_id", nullable = false)
	public int getAccountCategoryId() {
		return this.accountCategoryId;
	}

	public void setAccountCategoryId(int accountCategoryId) {
		this.accountCategoryId = accountCategoryId;
	}

	@Column(name = "water_value")
	public Integer getWaterValue() {
		return this.waterValue;
	}

	public void setWaterValue(Integer waterValue) {
		this.waterValue = waterValue;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "record_time", nullable = false, length = 19)
	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	@Column(name = "create_user_id", nullable = false)
	public int getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(int createUserId) {
		this.createUserId = createUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
