package com.nan.ia.server.db.entities;

// Generated 2015-6-4 16:01:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountBookMemberTblId generated by hbm2java
 */
@Embeddable
public class AccountBookMemberTblId implements java.io.Serializable {

	private int accountBookId;
	private int memberUserId;

	public AccountBookMemberTblId() {
	}

	public AccountBookMemberTblId(int accountBookId, int memberUserId) {
		this.accountBookId = accountBookId;
		this.memberUserId = memberUserId;
	}

	@Column(name = "account_book_id", nullable = false)
	public int getAccountBookId() {
		return this.accountBookId;
	}

	public void setAccountBookId(int accountBookId) {
		this.accountBookId = accountBookId;
	}

	@Column(name = "member_user_id", nullable = false)
	public int getMemberUserId() {
		return this.memberUserId;
	}

	public void setMemberUserId(int memberUserId) {
		this.memberUserId = memberUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountBookMemberTblId))
			return false;
		AccountBookMemberTblId castOther = (AccountBookMemberTblId) other;

		return (this.getAccountBookId() == castOther.getAccountBookId())
				&& (this.getMemberUserId() == castOther.getMemberUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountBookId();
		result = 37 * result + this.getMemberUserId();
		return result;
	}

}
