package com.nan.ia.server.db.entities;

// Generated 2015-5-18 15:27:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountBookMemberTbl generated by hbm2java
 */
@Entity
@Table(name = "account_book_member_tbl", catalog = "intimate_account_db")
public class AccountBookMemberTbl implements java.io.Serializable {

	private AccountBookMemberTblId id;
	private Date updateTime;

	public AccountBookMemberTbl() {
	}

	public AccountBookMemberTbl(AccountBookMemberTblId id, Date updateTime) {
		this.id = id;
		this.updateTime = updateTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "accountBookId", column = @Column(name = "account_book_id", nullable = false)),
			@AttributeOverride(name = "memberUserId", column = @Column(name = "member_user_id", nullable = false)) })
	public AccountBookMemberTblId getId() {
		return this.id;
	}

	public void setId(AccountBookMemberTblId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
