package com.nan.ia.server.db.entities;

// Generated 2015-5-17 18:02:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountCategoryTbl generated by hbm2java
 */
@Entity
@Table(name = "account_category_tbl", catalog = "intimate_account_db")
public class AccountCategoryTbl implements java.io.Serializable {

	private Integer accountCategoryId;
	private int accountBookId;
	private String category;
	private String superCategory;
	private Date createTime;
	private Date updateTime;

	public AccountCategoryTbl() {
	}

	public AccountCategoryTbl(int accountBookId, String category) {
		this.accountBookId = accountBookId;
		this.category = category;
	}

	public AccountCategoryTbl(int accountBookId, String category,
			String superCategory, Date createTime, Date updateTime) {
		this.accountBookId = accountBookId;
		this.category = category;
		this.superCategory = superCategory;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "account_category_id", unique = true, nullable = false)
	public Integer getAccountCategoryId() {
		return this.accountCategoryId;
	}

	public void setAccountCategoryId(Integer accountCategoryId) {
		this.accountCategoryId = accountCategoryId;
	}

	@Column(name = "account_book_id", nullable = false)
	public int getAccountBookId() {
		return this.accountBookId;
	}

	public void setAccountBookId(int accountBookId) {
		this.accountBookId = accountBookId;
	}

	@Column(name = "category", nullable = false, length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "super_category", length = 45)
	public String getSuperCategory() {
		return this.superCategory;
	}

	public void setSuperCategory(String superCategory) {
		this.superCategory = superCategory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
