package com.nan.ia.server.db.entities;

// Generated 2015-5-21 14:20:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginAccountTbl generated by hbm2java
 */
@Entity
@Table(name = "login_account_tbl", catalog = "intimate_account_db")
public class LoginAccountTbl implements java.io.Serializable {

	private LoginAccountTblId id;
	private String password;
	private int userId;
	private Date createTime;
	private Date updateTime;

	public LoginAccountTbl() {
	}

	public LoginAccountTbl(LoginAccountTblId id, String password, int userId,
			Date createTime, Date updateTime) {
		this.id = id;
		this.password = password;
		this.userId = userId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "accountType", column = @Column(name = "account_type", nullable = false)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 45)) })
	public LoginAccountTblId getId() {
		return this.id;
	}

	public void setId(LoginAccountTblId id) {
		this.id = id;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
