package com.nan.ia.server.db.entities;

// Generated 2015-5-21 14:20:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginStateTbl generated by hbm2java
 */
@Entity
@Table(name = "login_state_tbl", catalog = "intimate_account_db")
public class LoginStateTbl implements java.io.Serializable {

	private int userId;
	private String token;
	private Date updateTime;

	public LoginStateTbl() {
	}

	public LoginStateTbl(int userId, String token, Date updateTime) {
		this.userId = userId;
		this.token = token;
		this.updateTime = updateTime;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "token", nullable = false, length = 45)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
