package com.nan.ia.server.db.entities;

// Generated 2015-5-12 0:15:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserTbl generated by hbm2java
 */
@Entity
@Table(name = "user_tbl", catalog = "intimate_account_db")
public class UserTbl implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private String nickname;
	private String description;
	private Date updateTime;
	private Date createTime;

	public UserTbl() {
	}

	public UserTbl(String username, String password, String nickname,
			Date updateTime) {
		this.username = username;
		this.password = password;
		this.nickname = nickname;
		this.updateTime = updateTime;
	}

	public UserTbl(String username, String password, String nickname,
			String description, Date updateTime, Date createTime) {
		this.username = username;
		this.password = password;
		this.nickname = nickname;
		this.description = description;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nickname", nullable = false, length = 45)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 0)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
